version: "3.8"

services:
    www:
        build: ./front-edromo/
        restart: unless-stopped
        environment:
            ASPNET_HOST: 127.0.0.1
        ports: 
            - "0.0.0.0:3000:3000"
        develop: 
            watch:
                - action: sync
                  path: ./front-edromo
                  target: /app
                  initial_sync: true
                  ignore:
                    - node_modules/
                    - .next/
                    - .idea/
        depends_on:
            - aspnet
        networks:
            - frontend
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
    aspnet:
        build: ./Backend/EventodromoRest/
        restart: unless-stopped
        environment:
            PMA_HOST: localhost
            PMA_USER: admin
            PMA_PASSWORD: 12345
        ports:
            - "8080:8080"
        networks:
            - frontend
            - backend
       # healthcheck:
    #        test: ["CMD", "curl", "-f", "http://localhost"]
       #     interval: 10s
   #         timeout: 5s
     #       retries: 5

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
        internal: true

volumes:
    persistent:
