version: "3.8"

services:
    db:
        build: ./sql/
        restart: unless-stopped
        ports: 
            - "127.0.0.1:1433:1433"
        #command: --default-authentication-plugin=mysql_native_password
        environment:
            ACCEPT_EULA: "Y" 
            MSSQL_SA_PASSWORD: T8m!r2xZ
        volumes:
            - ./sql/myDb.sql:/myDb.sql
            - ./sql/init.sh:/init.sh
            #- persistent:/var/lib/mysql
        networks:
            - backend
        entrypoint: ["/bin/bash", "/init.sh"]

    www:
        build: ./front-edromo/
        restart: unless-stopped
        environment:
            ASPNET_HOST: 127.0.0.1
        ports: 
            - "0.0.0.0:3000:3000"
       # volumes:
       #     - ./Frontend:/app
        depends_on:
            - aspnet
            - db
        networks:
            - frontend
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    aspnet:
        build: ./Backend/EventodromoRest/
        restart: unless-stopped
        environment:
            PMA_HOST: localhost
            PMA_USER: admin
            PMA_PASSWORD: 12345
        ports:
            - "0.0.0.0:8080:8080"
        depends_on:
            - db
        networks:
            - frontend
            - backend
       # healthcheck:
    #        test: ["CMD", "curl", "-f", "http://localhost"]
       #     interval: 10s
   #         timeout: 5s
     #       retries: 5

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
        internal: true

volumes:
    persistent:
