DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS AUDITORIA_UPDATE;
DROP TABLE IF EXISTS AUDITORIA_INSERT;
DROP TABLE IF EXISTS AUDITORIA_DELETE;
GO

-- TABLA USUARIO
CREATE TABLE USUARIO (
    ID                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,   -- IDENTIFICADOR ÚNICO
    CORREO            VARCHAR(255)  NOT NULL,                   -- CORREO (ÚNICO)
    CONTRASENA        VARCHAR(255)  NOT NULL,                   -- HASH/CONTRASEÑA
    ROL               VARCHAR(1)    NOT NULL,                   -- ROL
    NOMBRES           VARCHAR(255)  NOT NULL,                   -- NOMBRES
    APELLIDOS         VARCHAR(255)  NOT NULL,                   -- APELLIDOS
    DNI               VARCHAR(20)   NOT NULL,                   -- DNI (ÚNICO)
    TELEFONO          VARCHAR(15)   NULL,                       -- TELÉFONO
    ESTADO            VARCHAR(1)    NULL,
    FECHA_ULT_MODIF   DATETIME      NOT NULL,                   -- ÚLTIMA MODIF
    USUARIO_ULT_MODIF VARCHAR(255)  NOT NULL                    -- USUARIO QUE MODIFICÓ
);
GO

-- TABLA AUDITORIA_UPDATE
CREATE TABLE AUDITORIA_UPDATE (
    ID                           INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TABLA                        VARCHAR(255) NOT NULL,
    ID_ENTIDAD                   INT NOT NULL,
    CAMPO                        VARCHAR(255) NOT NULL,
    VALOR_NUEVO                  VARCHAR(255) NULL,
    VALOR_ANTERIOR               VARCHAR(255) NULL,
    USUARIO_AUDITORIA_NUEVO      VARCHAR(255) NOT NULL,
    USUARIO_AUDITORIA_ANTERIOR   VARCHAR(255) NOT NULL,
    FECHA_AUDITORIA_NUEVO        DATETIME NOT NULL,
    FECHA_AUDITORIA_ANTERIOR     DATETIME NOT NULL
);
GO

-- TABLA AUDITORIA_INSERT
CREATE TABLE AUDITORIA_INSERT (
    ID          INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TABLA       VARCHAR(255) NOT NULL,
    ID_ENTIDAD  INT NOT NULL,
    FECHA       DATETIME NOT NULL,
    USUARIO     VARCHAR(255) NOT NULL
);
GO

-- TABLA AUDITORIA_DELETE
CREATE TABLE AUDITORIA_DELETE (
    ID          INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TABLA       VARCHAR(255) NOT NULL,
    ID_ENTIDAD  INT NOT NULL,
    FECHA       DATETIME NOT NULL CONSTRAINT DF_AD_FECHA DEFAULT (GETDATE()),
    USUARIO     VARCHAR(255) NOT NULL
);
GO