IF DB_ID('EVENTO') IS NULL
    CREATE DATABASE EVENTO;
GO
USE EVENTO;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'DEMO')
    EXEC('CREATE SCHEMA DEMO AUTHORIZATION dbo;');
GO

IF OBJECT_ID('DEMO.USUARIO', 'U') IS NOT NULL
    DROP TABLE DEMO.USUARIO;
GO

CREATE TABLE DEMO.USUARIO (
    ID                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CORREO            VARCHAR(255)  NOT NULL,
    CONTRASENA        VARCHAR(255)  NOT NULL,
    ROL               VARCHAR(1)    NOT NULL,
    NOMBRES           VARCHAR(255)  NOT NULL,
    APELLIDOS         VARCHAR(255)  NOT NULL,
    DNI               VARCHAR(20)   NOT NULL,
    TELEFONO          VARCHAR(15)   NULL,
    ESTADO            VARCHAR(1)    NOT NULL,
    FECHA_ULT_MODIF   DATETIME      NOT NULL,
    USUARIO_ULT_MODIF VARCHAR(255)  NOT NULL,
);
GO

INSERT INTO DEMO.USUARIO
(CORREO, CONTRASENA, ROL, NOMBRES, APELLIDOS, DNI, TELEFONO, ESTADO, FECHA_ULT_MODIF, USUARIO_ULT_MODIF)
VALUES
('juan.perez@mail.com',   'HashPass123', 'A', 'Juan',   'Pérez',           '12345678', '999111222', 1, '2025-09-14T22:54:04.827', 'admin'),
('maria.garcia@mail.com', 'HashPass456', 'U', 'María',  'García López',    '87654321', '988777666', 1, '2025-09-14T22:54:04.827', 'admin'),
('carlos.rosas@mail.com', 'HashPass789', 'U', 'Carlos', 'Rosas Fernández', '11223344', NULL,         0, '2025-09-14T22:54:04.827', 'admin');
GO
